### ISSUE TITLE
DocumentFilter

### ISSUE THREAD

**Issue by BeckySharp** [ml4ai/automates#12]
when we parse arxiv pdfs with science parse, the first page seems to get the sideways watermark in the document pretty consistently:

```
The federated learning learns a shared global model by the aggregation of local models 
on client devices. But in the original paper of federated learning [18] only uses a simple 
average on client models, taking the number of samples in each client device as the 
weight of averaging. In the mobile keyboard applications, the language preference may 
vary from different individuals. There is a relation among the client
ar X
iv :1
81 2.
07 10
8v 1
[ cs
.C L
] 1
7 D
ec 2
01 8
language models, and their contributions to the central server are quite different. 
```

Since we're primarily using arxiv papers, I think we should removed this, prob with a [DocumentFilter](https://github.com/ml4ai/automates/blob/master/text_reading/src/main/scala/org/clulab/utils/DocumentFilter.scala)

**Comment by maxaalexeeva** [comment]
Pretty sure this has been filtered out. Plus, not using science-parse much right now.
