### ISSUE TITLE
broken link for equation extraction documentation

### ISSUE THREAD

**Issue by myedibleenso** [ml4ai/automates#143]
The equation extraction documentation linked from [this file](https://github.com/ml4ai/automates/blob/6b8832f5bcd80a6efb45a677613adb1634e44c90/docs/software.md) appears to be broken:

- https://ml4ai.github.io/automates/equation_extraction/README/

**Comment by adarshp** [comment]
Thanks for letting us know @myedibleenso !

@pauldhein can you update the documentation to point to the correct location when you get a chance? Thanks!

**Comment by pauldhein** [comment]
It looks like a lot of the documentation links are still broken. I am going to build/test this locally and then merge a working version into master. @myedibleenso sorry for pre-maturely closing this issue.

**Comment by pauldhein** [comment]
Alright the link is fixed now, sorry for the confusion!
