### ISSUE TITLE
filtering out units that look like variables

### ISSUE THREAD

**Issue by alicekwak** [ml4ai/automates#183]
d-1 and h-1 are extracted as variables in the example below, but there shouldn't be.

`ETsz = standardized reference crop evapotranspiration for short (ETos) or tall (ETrs) surfaces (mm d-1 for daily time steps or mm h-1 for hourly time steps),`

**Comment by maxaalexeeva** [comment]
Filtered these out, probably with the looksLikeAnIdentifier action.
